// generated by sapper build at 2020-01-05T22:44:52.954Z
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.PORT = process.env.PORT || 80;

console.log('Starting server on port ' + process.env.PORT);
require('./server/server.js');